name: Docker Build and Push

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

// ... existing checkout and QEMU setup ...

    - name: Log into ghcr.io registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Build Docker Metadata
      id: docker-metadata
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        flavor: |
          latest=auto
        tags: |
          type=sha,commit=${{ github.sha }}
          type=ref,event=branch
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Push Service Image to repo
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        provenance: mode=max
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}